"""add ondelete cascade

Revision ID: 3f7ba67fa561
Revises: 0f16031f6b94
Create Date: 2023-08-29 11:32:29.865941

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '3f7ba67fa561'
down_revision = '0f16031f6b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profession_parent_id_fkey', 'profession', type_='foreignkey')
    op.drop_constraint('profession_sphere_id_fkey', 'profession', type_='foreignkey')
    op.create_foreign_key(None, 'profession', 'sphere', ['sphere_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profession', 'profession', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profession_translation_profession_id_fkey', 'profession_translation', type_='foreignkey')
    op.create_foreign_key(None, 'profession_translation', 'profession', ['profession_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('resume_profession_id_fkey', 'resume', type_='foreignkey')
    op.create_foreign_key(None, 'resume', 'profession', ['profession_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sphere_translation_sphere_id_fkey', 'sphere_translation', type_='foreignkey')
    op.create_foreign_key(None, 'sphere_translation', 'sphere', ['sphere_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sphere_translation', type_='foreignkey')
    op.create_foreign_key('sphere_translation_sphere_id_fkey', 'sphere_translation', 'sphere', ['sphere_id'], ['id'])
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.create_foreign_key('resume_profession_id_fkey', 'resume', 'profession', ['profession_id'], ['id'])
    op.drop_constraint(None, 'profession_translation', type_='foreignkey')
    op.create_foreign_key('profession_translation_profession_id_fkey', 'profession_translation', 'profession', ['profession_id'], ['id'])
    op.drop_constraint(None, 'profession', type_='foreignkey')
    op.drop_constraint(None, 'profession', type_='foreignkey')
    op.create_foreign_key('profession_sphere_id_fkey', 'profession', 'sphere', ['sphere_id'], ['id'])
    op.create_foreign_key('profession_parent_id_fkey', 'profession', 'profession', ['parent_id'], ['id'])
    # ### end Alembic commands ###
