"""add unique constraint

Revision ID: 0f16031f6b94
Revises: 028248bae54b
Create Date: 2023-08-25 15:57:15.047443

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '0f16031f6b94'
down_revision = '028248bae54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profession_translation', ['profession_id', 'language_id'])
    op.create_unique_constraint(None, 'sphere_translation', ['sphere_id', 'language_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sphere_translation', type_='unique')
    op.drop_constraint(None, 'profession_translation', type_='unique')
    # ### end Alembic commands ###
