"""add is active

Revision ID: 4e5adc236128
Revises: dc5f23f82e8c
Create Date: 2023-08-21 12:43:32.799840

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '4e5adc236128'
down_revision = 'dc5f23f82e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profession', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('sphere', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sphere', 'is_active')
    op.drop_column('profession', 'is_active')
    # ### end Alembic commands ###
