"""remove nullable from certificate name

Revision ID: 62b1ed660809
Revises: 2d50295f377f
Create Date: 2023-08-03 11:46:26.165964

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '62b1ed660809'
down_revision = '2d50295f377f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_block', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_block', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
