"""add models

Revision ID: 808d0f413d9d
Revises: 156b50a8591f
Create Date: 2023-07-28 17:32:45.178846

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '808d0f413d9d'
down_revision = '156b50a8591f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_block_resume_id_fkey', 'course_block', type_='foreignkey')
    op.create_foreign_key(None, 'course_block', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('education_block_resume_id_fkey', 'education_block', type_='foreignkey')
    op.create_foreign_key(None, 'education_block', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('experience_block_resume_id_fkey', 'experience_block', type_='foreignkey')
    op.create_foreign_key(None, 'experience_block', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('language_block_resume_id_fkey', 'language_block', type_='foreignkey')
    op.create_foreign_key(None, 'language_block', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'media', ['filename'])
    op.drop_constraint('portfolio_link_block_resume_id_fkey', 'portfolio_link_block', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_link_block', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('skill_block_resume_id_fkey', 'skill_block', type_='foreignkey')
    op.create_foreign_key(None, 'skill_block', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('social_link_block_resume_id_fkey', 'social_link_block', type_='foreignkey')
    op.create_foreign_key(None, 'social_link_block', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_link_block', type_='foreignkey')
    op.create_foreign_key('social_link_block_resume_id_fkey', 'social_link_block', 'resume', ['resume_id'], ['id'])
    op.drop_constraint(None, 'skill_block', type_='foreignkey')
    op.create_foreign_key('skill_block_resume_id_fkey', 'skill_block', 'resume', ['resume_id'], ['id'])
    op.drop_constraint(None, 'portfolio_link_block', type_='foreignkey')
    op.create_foreign_key('portfolio_link_block_resume_id_fkey', 'portfolio_link_block', 'resume', ['resume_id'], ['id'])
    op.drop_constraint(None, 'media', type_='unique')
    op.drop_constraint(None, 'language_block', type_='foreignkey')
    op.create_foreign_key('language_block_resume_id_fkey', 'language_block', 'resume', ['resume_id'], ['id'])
    op.drop_constraint(None, 'experience_block', type_='foreignkey')
    op.create_foreign_key('experience_block_resume_id_fkey', 'experience_block', 'resume', ['resume_id'], ['id'])
    op.drop_constraint(None, 'education_block', type_='foreignkey')
    op.create_foreign_key('education_block_resume_id_fkey', 'education_block', 'resume', ['resume_id'], ['id'])
    op.drop_constraint(None, 'course_block', type_='foreignkey')
    op.create_foreign_key('course_block_resume_id_fkey', 'course_block', 'resume', ['resume_id'], ['id'])
    # ### end Alembic commands ###
