"""add models

Revision ID: ce80f38b0d75
Revises: 4ec26d4487e0
Create Date: 2023-08-22 12:12:24.971273

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = 'ce80f38b0d75'
down_revision = '4ec26d4487e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profession', 'sphere_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profession', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profession', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profession', 'sphere_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
