"""add template id

Revision ID: c980fca17fd4
Revises: 62b1ed660809
Create Date: 2023-08-18 10:05:04.339026

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = 'c980fca17fd4'
down_revision = '62b1ed660809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('template_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'template_id')
    # ### end Alembic commands ###
