"""change template id type to int

Revision ID: 5707439e9f1c
Revises: c980fca17fd4
Create Date: 2023-08-18 11:46:35.674091

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '5707439e9f1c'
down_revision = 'c980fca17fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
