"""add language_id

Revision ID: 5156837e0fab
Revises: 3a86d95a24ea
Create Date: 2023-08-23 10:52:58.793367

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '5156837e0fab'
down_revision = '3a86d95a24ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profession_translation', sa.Column('language_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('sphere_translation', sa.Column('language_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sphere_translation', 'language_id')
    op.drop_column('profession_translation', 'language_id')
    # ### end Alembic commands ###
