"""add models

Revision ID: 917690577d4a
Revises: 299e3bd55c1e
Create Date: 2023-08-02 12:14:26.259346

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '917690577d4a'
down_revision = '299e3bd55c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('media_filename_key', 'media', type_='unique')
    op.create_unique_constraint(None, 'media', ['path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='unique')
    op.create_unique_constraint('media_filename_key', 'media', ['filename'])
    # ### end Alembic commands ###
