"""add unique is default

Revision ID: 028248bae54b
Revises: 5156837e0fab
Create Date: 2023-08-23 11:57:33.520611

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '028248bae54b'
down_revision = '5156837e0fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('only_one_active_is_default', 'profession', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('only_one_active_is_default', table_name='profession', postgresql_where=sa.text('is_default'))
    # ### end Alembic commands ###
